name: Auto name images & build images.json

on:
  push:
    paths:
      - 'assets/**'
      - '.github/workflows/auto-name-and-list.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rename_and_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug – list assets before
        run: |
          echo "Before:"
          ls -la assets || echo "No assets folder"

      - name: Auto-rename assets and rebuild images.json
        run: |
          python3 - << 'PY'
import os, re, json, time

ASSETS = "assets"
KEEP_EXTS = {"png","jpg","jpeg","webp","avif"}
CANON = re.compile(r'^OW_(\d{3})\.(png|jpg|jpeg|webp|avif)$', re.I)

os.makedirs(ASSETS, exist_ok=True)

# Collect all candidate files (flat in assets/, ignore 'optimized' folder)
candidates = []
for f in os.listdir(ASSETS):
    if f.lower() == "optimized":
        continue
    p = os.path.join(ASSETS, f)
    if not os.path.isfile(p):
        continue
    ext = f.rsplit(".",1)[-1].lower() if "." in f else ""
    if ext in KEEP_EXTS:
        candidates.append((p, f, ext, os.stat(p).st_mtime))

# Find already canonical names
used = set()
for _, f, _, _ in candidates:
    m = CANON.match(f)
    if m:
        used.add(int(m.group(1)))

next_idx = max(used) if used else 0

changes = []
# Rename any non-canonical file to next OW_###
for p, f, ext, mtime in sorted(candidates, key=lambda t: t[3]):  # oldest first
    if CANON.match(f):
        continue
    next_idx += 1
    new = f"OW_{next_idx:03d}.{ext}"
    os.rename(p, os.path.join(ASSETS, new))
    changes.append((f, new))

# Build images.json (sorted by numeric index)
entries = []
for f in os.listdir(ASSETS):
    m = CANON.match(f)
    if m:
        entries.append((int(m.group(1)), f))
entries.sort(key=lambda t: t[0])

with open("images.json","w",encoding="utf-8") as fh:
    json.dump([f"assets/{name}" for _, name in entries], fh, indent=2, ensure_ascii=False)

print("Renamed files:", changes)
print("Total images:", len(entries))
PY

      - name: Debug – list assets after & show images.json
        run: |
          echo "After:"
          ls -la assets
          echo
          echo "images.json:"
          cat images.json

      - name: Commit changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets images.json || true
          git commit -m "Auto-rename assets & update images.json" || echo "No changes"
          git push
